### ISSUE TITLE
Empty sitemap

### ISSUE THREAD

**Issue by thegregthomp** [joshuabaker/craft-sitemap#29]
The sitemap.xml file is generated but the sitemap is still empty, Any ideas? I tried this version and @groe version. 

![image](https://cloud.githubusercontent.com/assets/1554124/20845862/0ee4bbac-b895-11e6-8eb0-c53879bec213.png)

**Comment by groe** [comment]
Not sure what's the problem here but some guesses:

* Is the sitemap.xml file you see actually generated by craft-sitemap? Make sure there is no static file with that name (or other plugin registered for that route).
* Are your entries published?
* Is it a multi-locale site? If so, what's the URL schema?

**Comment by thegregthomp** [comment]
@groe, thanks for the response/help! the sitemap.xml is def. published by the plugin because when I disable I get a 404. Secondly yes, I've added this plugin to an existing site that has multiple channels/entries. Lastly, it's not a multi-locale site, it's a pretty basic Craft build.

**Comment by groe** [comment]
Hm, that's strange. Is craft up-to-date? What PHP version are you using? Is there anything in the log files? Can you reproduce the issue with a clean/reduced craft site somehow, which you can push to github?

**Comment by billythekid** [comment]
FWIW I was experiencing this today on a site where the siteUrl was set as a relative url to handle any protocol. The plugin was erroring with with `Craft\Sitemap_AlternateUrlModel->href failed validation: Href is not a valid URL.`

changing the siteUrl from 
`'//' . $_SERVER['HTTP_HOST'] . '/'` 
to 
`'http://' . $_SERVER['HTTP_HOST'] . '/'` 
got the sitemap.xml file to populate.

I think the validation is a bit too strict is all that's happening here.

HTH

**Comment by joshuabaker** [comment]
@billythekid, a missing protocol wouldn’t validate, even if this is accepted by browsers. The plugin uses the Yii URL validator.

You might consider making the protocol dynamic, wherever you’re setting it.

**Comment by katrinkerber** [comment]
Have used this plugin for many sites without problems in the past but I am experiencing the same issue with my latest site. The logs error message is also: `Craft\Sitemap_AlternateUrlModel->href failed validation: Href is not a valid URL.`.

This site is a multi-locale one and also runs on https. Do I need to do something special to get this working?

**Comment by benjaminleeschnell** [comment]
I'm getting an empty sitemap as well at maseriouscare.org/sitemap.xml. Here's what I'm seeing:
 
<img width="1280" alt="screen shot 2017-04-13 at 10 08 56 am" src="https://cloud.githubusercontent.com/assets/8826098/25008289/40a7d9c2-2031-11e7-8513-6df91efed92f.png">

<img width="1280" alt="screen shot 2017-04-13 at 10 07 02 am" src="https://cloud.githubusercontent.com/assets/8826098/25008231/1c78ff90-2031-11e7-96fb-50f19a602b4c.png">

**Comment by winter-mike** [comment]
This is happening for me also.

It was previously working, until i added a single entry/section called sitemap, have since removed the entry/section and related templates but above issue still persists. Could be a coincidence, i really don't know what the issue is.

![screen shot 2017-05-31 at 15 44 15](https://cloud.githubusercontent.com/assets/1919297/26637920/b129b384-4618-11e7-9d2a-5e6b30fb3b4e.png)
![screen shot 2017-05-31 at 15 44 41](https://cloud.githubusercontent.com/assets/1919297/26637919/b0f1471a-4618-11e7-9edd-b78ab9fe843e.png)

**Comment by winter-mike** [comment]
Actually, i managed to get this working again.

I added the `http` protocol to my `siteUrl` settings in my `craft/config/general.php` file and all works again for me.

Thanks

**Comment by benjaminleeschnell** [comment]
Yes, good call. Adding http to the siteUrl settings fixed it for me as well. Thanks for the heads up @michaelhwinter

**Comment by yellowmamba** [comment]
I am facing the exact same issue. My temporary solution is to return true from Sitemap_BaseModel::validate().
```
abstract class Sitemap_BaseModel extends BaseModel
{
    /**
     * Throws exceptions for validation errors when in devMode.
     *
     * @return bool
     */
    public function validate($attributes = null, $clearErrors = true)
    {
        return true;
        // $validate = parent::validate($attributes, $clearErrors);

        // if (!$validate && craft()->config->get('devMode')) {
        //     foreach ($this->getAllErrors() as $attribute => $error) {
        //         throw new Exception(Craft::t($error));
        //     }
        // }

        // return $validate;
    }
}
```
Or to override this method in `Sitemap_UrlModel` class.

I think Yii is crawling all `href` links on a page and try to verify if the value conforms to the valid URL format. If your page contains an anchor tag like `<a href="#close">`, this page would fail the validation. I am not 100% sure about this, but I really don't have time to further investigate into this.

**Comment by sarahtooley** [comment]
Adding http and our site url did not work for me (maybe because I'm on localhost currently?), but I tried @yellowmamba 's tactic and it worked.

Looking into it further, our page URLs were being shown as '**`/en/some-link`**' as opposed to '**`https://www.ourwebsite.com/en/some-link`**'. For now, I added our site URL to the **UrlModel** and **AlternateUrlModel**. When I reactivate the Yii validation, it now passes.

`UrlModel

    public function __construct($loc, $lastmod, $changefreq = null, $priority = null)
    {
        $this->loc = "https://www.ourwebsite.com".$loc;
        $this->lastmod = $lastmod;
        $this->changefreq = $changefreq;
        $this->priority = $priority;
    }
`

`AlternateUrlModel

    public function __construct($hreflang = null, $href = null)
    {
        $this->hreflang = $hreflang;
        $this->href = "https://www.ourwebsite.com".$href;
    }`

Longer term solution is to update that config file as opposed to manually inputting here.
